### ISSUE TITLE
Homework feedback - HTML/CSS - week 1

### ISSUE THREAD

**Issue by senner008** [krithi-kondana/hyf-homework#1]
Hi ;)
Homework looks good. I see you already have a good understanding of html and css. 
Great with the table and the iframe
You also thought about your layout and how to position stuff on a page. This takes time to learn. Please look at the comments in the commit and ask if you have any questions.

**Comment by krithi-kondana** [comment]
Thank you for your your feedback @senner008 
I will try to implement the ideas based on your comments.
