### ISSUE TITLE
Very elegant solution

### ISSUE THREAD

**Issue by aleks-hyf** [krithi-kondana/hyf-homework#16]
https://github.com/krithi-kondana/hyf-homework/blob/fe5f3e1473dad88f2ace500a4c752276526ed02f/javascript/javascript2/week2/movies/movies.js#L120

This has a plus - as your code is compact and does the job, but it also becomes harder to read and understand the logic. Anyways, as long as you understand well how and why this code works, that's great and keep it up.

**Comment by krithi-kondana** [comment]
Hi @aleks-hyf , I am really thankful to you for going through the codes so carefully and reviewing even the minute details. I will surely take care about naming the variables properly hereafter.
