### ISSUE TITLE
Homework Feedback - HTML/CSS - week 2

### ISSUE THREAD

**Issue by susaneme** [krithi-kondana/hyf-homework#2]
Hi Krithi :)

First of all I would like to say that you got the most subtle requirement of this exercise 😀 ! I felt sooo glad  when  I scaled down to see how it was on smaller devices the section ‘Practical Web Development’ was the first thing, below the image, I saw! 😻 You completed the requirement of changing the order of the elements on mobile, not just making it responsive but also playing around with its order! Congratulations for having such a detail-oriented perception and also to accomplish that technically. A hug clap of hands for you 👏 . I have some few observations that are more like advices and best practices: 
- Your site functions nicely, but I would encourage you to use semantic tags for accomplishing some goals, for example you could eliminate a lot of code both in your HTML and CSS but just replacing certain `div` For semantic tags, example `  <div class="header-container"> <div class="header"> ` this could have been just one single `<header></header>` tag , the same for `<div class="navigation-container"><div class="navigation"> ` by using `<nav></nav>`, and footer as well 🙃 
- In terms of classes I would suggest you two things: give your classes a meaningful name, so it is easier to maintain and understanding what is the purpose of that identifier, for example `<div class="part2"> ` could be `<div class="about">`
- For the google maps you could try to get more interactive by using something like you can find [here](https://www.embedgooglemap.net/), so you can just get a understanding how it works 😋 ... 
- Just an extra observation, try to organize your images in a folder, so you dont have all your code, styles and other resources in th root folder 🙃 

To finish: Really Well DONE! You applied a lot of concepts learned in class, which is awesome! Keep doing great like this 😍 🥇 💯 🌷

**Comment by krithi-kondana** [comment]
thank you @susaneme for the feedback:) I will surely keep these things in mind hereafter :)
