### ISSUE TITLE
Homework Feedback - HTML/CSS - week 3

### ISSUE THREAD

**Issue by senner008** [krithi-kondana/hyf-homework#4]
Hi :)
Great homework!
Just a few íssues with duplicate id and name attr. Read the comments.
Also try to find a way to use placeholder and inform user about specific requirements
Otherwise very good.
Keep it up!

**Comment by krithi-kondana** [comment]
Thank you for the feedback @senner008 
I read the comments. I will follow accordingly.
Regarding placeholder, i thought i will do it at the end before submission. But at the time of submission i forgot. :-(
