### ISSUE TITLE
Homework Feedback - JS1-week1

### ISSUE THREAD

**Issue by Swapna-Sahu** [krithi-kondana/hyf-homework#5]
Hi,
Good Job! 👍  I can see you have done lot of research calculating dog age. That's great. 

In the homework, we have given the logic to how to calculate dog age. Which is not fully correct but we like to keep it simple for you guys :)

Please edit your homework using logic mentioned in homework. 
dogAgeInDogYear = (dogYearFuture - dogYearOfBirth);
dogAgeInHumanYear = (dogYearFuture - dogYearOfBirth)* 7;
It is simple . right ?

Everything looks prefect. Keep it up 🥇

**Comment by krithi-kondana** [comment]
Hey swapna
Thanks for the feedback :-) Actually i didnt notice the above logic in the homework :( Thats why i ended up doing that long calculation. I will do it as you said. :+1:

**Comment by krithi-kondana** [comment]
Hey swapna, I did the changes. Please have a look at it.

**Comment by Swapna-Sahu** [comment]
Looks good to me 👍
